workflow:
  rules:
    - changes:
        - CMakeLists.txt
        - src/**/*
        - .gitlab-ci.yml
      when: always
    - when: never

image: stalhrim/build-essential

stages:
  - build
  - test

build-nox:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DINCLUDE_TEST=ON -DNOCURSOR=ON ..
    - make -j$(nproc)
  artifacts:
    paths:
      - build/src/tests/*_test
    when: on_success
    expire_in: 5 min

build-nogui:
  stage: build
  image: stalhrim/build-x11
  script:
    - mkdir build
    - cd build
    - cmake -DINCLUDE_TEST=OFF ..
    - make -j$(nproc)

build-full:
  stage: build
  image: stalhrim/build-x11-qt5
  script:
    - mkdir build
    - cd build
    - cmake -DINCLUDE_TEST=OFF ..
    - make -j$(nproc)

event_testing:
  stage: test
  script:
    - build/src/tests/event_test
  when: manual # unable to use uinput module
  except:
    refs:
      - windows

network_testing:
  stage: test
  needs: ["build-nox"]
  script:
    - build/src/tests/network_test
  except:
    refs:
      - windows

localcom_testing:
  stage: test
  needs: ["build-nox"]
  script:
    - mkdir -p /var/lib/rsc/
    - build/src/tests/localcom_test
  except:
    refs:
      - windows

common_testing:
  stage: test
  needs: ["build-nox"]
  script:
    - mkdir -p /var/lib/rsc/
    - build/src/tests/common_test
  except:
    refs:
      - windows

rsccli_testing:
  stage: test
  needs: ["build-nox"]
  script:
    - build/src/tests/rsccli_test
  except:
    refs:
      - windows
